# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_answer_correct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
