# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20170425_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='used',
            field=models.IntegerField(default=0),
        ),
    ]
